# Generated by Django 6.0.2 on 2026-02-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GenderEmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campus_assignment",
                    models.CharField(blank=True, max_length=22, null=True),
                ),
                (
                    "office_affiliation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "employment_status",
                    models.CharField(blank=True, max_length=31, null=True),
                ),
                (
                    "type_of_employee",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                ("sex", models.CharField(blank=True, max_length=6, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                (
                    "marital_status",
                    models.CharField(blank=True, max_length=9, null=True),
                ),
                ("years_in_service", models.IntegerField(blank=True, null=True)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_head_of_family", models.IntegerField(blank=True, null=True)),
                ("is_primary_caregiver", models.IntegerField(blank=True, null=True)),
                ("is_solo_parent", models.IntegerField(blank=True, null=True)),
                ("has_children_below_7", models.IntegerField(blank=True, null=True)),
                (
                    "has_children_with_disabilities",
                    models.IntegerField(blank=True, null=True),
                ),
                ("is_ip_member", models.IntegerField(blank=True, null=True)),
                ("is_pwd", models.IntegerField(blank=True, null=True)),
                ("pwd_types", models.CharField(blank=True, max_length=255, null=True)),
                ("household_size", models.IntegerField(blank=True, null=True)),
                (
                    "household_income_range",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("employee_id", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "gender_employee_profile",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("middlename", models.CharField(blank=True, max_length=100, null=True)),
                ("lastname", models.CharField(max_length=100)),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("otp_code", models.CharField(blank=True, max_length=6, null=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
    ]
